# Generated by Django 4.2.19 on 2025-03-08 23:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Доступное количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Количество позиции в заказе не может быть меньше 1."
                            )
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Оплачено", "PAID"),
                            ("В ожидании", "PENDING"),
                            ("Готово", "READY"),
                        ],
                        default="Оплачено",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Номер стола",
                    ),
                ),
                ("total_price", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="orders",
                        through="orders.ItemQuantity",
                        to="orders.item",
                        verbose_name="Позиции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="itemquantity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
